import homeController from "./homeController";
import authController from "./authController";
import userController from "./userController";
import contactController from "./contactController";
import notificationController from "./notificationController";
import messageController from "./messageController";
import groupChatController from "./groupChatController";
import adminUserController from "./adminController/userController";
import adminBackupController from "./adminController/backupController";
import adminChatController from "./adminController/chatController";
import adminGroupChatController from "./adminController/groupChatController";
export const home = homeController;
export const auth = authController;
export const user = userController;
export const contact = contactController;
export const notification = notificationController;
export const message = messageController;
export const groupChat = groupChatController;
export const adminUser = adminUserController;
export const backup = adminBackupController;
export const adminChat = adminChatController;
export const adminGroupChat = adminGroupChatController;
